# Category configuration drives what specs are extracted and how they are normalized.
# Each entry maps HTML label variants to a canonical internal attribute name.

CATEGORIES = {
    "microcontroller": {
        "important_attributes": [
            "architecture",
            "flash_kb",
            "ram_kb",
            "gpio_pins",
            "voltage_min",
            "voltage_max",
            "interfaces",
        ],
        # Maps raw HTML spec labels to canonical attribute names
        "html_spec_map": {
            "core": "architecture",
            "cpu": "architecture",
            "processor": "architecture",
            "flash": "flash_kb",
            "flash memory": "flash_kb",
            "program memory": "flash_kb",
            "program memory size": "flash_kb",
            "ram": "ram_kb",
            "sram": "ram_kb",
            "data ram": "ram_kb",
            "gpio": "gpio_pins",
            "gpio pins": "gpio_pins",
            "i/o pins": "gpio_pins",
            "number of i/os": "gpio_pins",
            "voltage": "voltage_range",
            "supply voltage": "voltage_range",
            "operating voltage": "voltage_range",
            "vcc": "voltage_range",
            "interface": "interfaces",
            "communication interface": "interfaces",
            "peripherals": "interfaces",
            "speed": "max_speed_mhz",
            "clock speed": "max_speed_mhz",
            "cpu speed": "max_speed_mhz",
            "max clock frequency": "max_speed_mhz",
            "package": "package_type",
            "package type": "package_type",
            "operating temperature": "temp_range",
            "temperature range": "temp_range",
        },
    },
    "sensor": {
        "important_attributes": [
            "sensor_type",
            "measurement_range",
            "accuracy",
            "interface",
            "voltage_min",
            "voltage_max",
            "output_type",
        ],
        "html_spec_map": {
            "sensor type": "sensor_type",
            "type": "sensor_type",
            "sensing element": "sensor_type",
            "measurement range": "measurement_range",
            "range": "measurement_range",
            "full scale range": "measurement_range",
            "accuracy": "accuracy",
            "resolution": "resolution",
            "interface": "interface",
            "output interface": "interface",
            "output type": "output_type",
            "output": "output_type",
            "supply voltage": "voltage_range",
            "operating voltage": "voltage_range",
            "vcc": "voltage_range",
            "operating temperature": "temp_range",
            "package": "package_type",
        },
    },
    "power_ic": {
        "important_attributes": [
            "topology",
            "input_voltage_min",
            "input_voltage_max",
            "output_voltage",
            "output_current_a",
            "switching_frequency_khz",
            "efficiency",
        ],
        "html_spec_map": {
            "topology": "topology",
            "converter type": "topology",
            "type": "topology",
            "input voltage": "input_voltage_range",
            "vin": "input_voltage_range",
            "input voltage range": "input_voltage_range",
            "output voltage": "output_voltage",
            "vout": "output_voltage",
            "output current": "output_current_a",
            "iout": "output_current_a",
            "maximum output current": "output_current_a",
            "switching frequency": "switching_frequency_khz",
            "frequency": "switching_frequency_khz",
            "efficiency": "efficiency",
            "package": "package_type",
            "operating temperature": "temp_range",
        },
    },
    "memory": {
        "important_attributes": [
            "memory_type",
            "capacity_mb",
            "interface",
            "voltage_min",
            "voltage_max",
            "speed",
        ],
        "html_spec_map": {
            "memory type": "memory_type",
            "type": "memory_type",
            "capacity": "capacity_mb",
            "density": "capacity_mb",
            "interface": "interface",
            "bus interface": "interface",
            "supply voltage": "voltage_range",
            "operating voltage": "voltage_range",
            "access time": "speed",
            "speed": "speed",
            "package": "package_type",
        },
    },
}
